[package]
name = "opt8n"
version = "0.1.0"
edition = "2021"

[dependencies]
op-test-vectors = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
color-eyre = { workspace = true }
anvil = { workspace = true }
forge-script = { workspace = true }
