[package]
name = "op-test-vectors"
version = "0.1.0"
edition = "2021"

[dependencies]
op-alloy-rpc-types = "0.1.2"
op-alloy-consensus = "0.1.2"
alloy = { version = "0.1", features = ["rpc", "rpc-types-trace"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"

[dev-dependencies]
eyre = "0.6.12"
